### ISSUE TITLE
As a developper I want a folder structure

### ISSUE THREAD

**Issue by almiche** [jusleg/storyflow#2]

**Comment by almiche** [comment]
@jusleg can you look into this ? Related to another issue

**Comment by jusleg** [comment]
Since we will most likely not maintain this, I believe we should keep the structure as is. It will be good to look back at this and see how we used to do things.

**Comment by almiche** [comment]
Indeed the future is a projection of the past. We must learn from our mistakes and move forward @jusleg @kcamcam
